services:
  minio:
    container_name: memes-minio
    image: "minio/minio:latest"
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
    command: server --console-address ":9090" /minio/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
    - type: bind
      source: /home/cutlery/coding/memes-test-task/minio/data
      target: /minio/data
    - type: bind
      source: /home/cutlery/coding/memes-test-task/minio/minio.env
      target: /minio/minio.env
