"""empty message

Revision ID: 03177b39dfab
Revises: 
Create Date: 2024-07-09 22:00:51.531180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03177b39dfab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=256), nullable=False),
    sa.Column('bucket_name', sa.String(length=256), nullable=False),
    sa.Column('etag', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memes')
    # ### end Alembic commands ###
